#!/usr/bin/env python3
from pathlib import Path

path = Path("Bridge/vex_bridge.py")
text = path.read_text(encoding="utf-8")
old = '''    if wants_browserish or wants_launch:\n        site_name = _candidate_site_name(request)\n        if site_name:\n            url = _resolve_site_via_web(site_name)\n            if url:\n                recipe = {"primitive": "open_url", "value": url}\n                result = _execute_skill_recipe(recipe)\n                if result.get("ok"):\n                    _remember_skill(request, recipe, "web-discovery")\n                    result["message"] = "learned web skill"\n                return result\n\n    folder = _resolve_existing_folder(request)\n    if folder:\n        recipe = {"primitive": "open_folder", "value": folder}\n        result = _execute_skill_recipe(recipe)\n        if result.get("ok"):\n            _remember_skill(request, recipe, "local-folder")\n            result["message"] = "learned folder skill"\n        return result\n\n    if wants_launch:\n        app_name = _candidate_app_name(request)\n        app_path = _resolve_installed_app(app_name)\n        if app_path:\n            recipe = {"primitive": "launch_app", "value": app_path}\n            result = _execute_skill_recipe(recipe)\n            if result.get("ok"):\n                _remember_skill(request, recipe, "installed-app-discovery")\n                result["message"] = "learned app skill"\n            return result\n\n    return {"ok": False, "node_name": node, "message": "no safe skill recipe found"}\n'''
new = '''    # Explicit browser/site language should prefer web discovery. Generic open/launch\n    # language should prefer a real installed app first so "open Audacity" doesn't\n    # accidentally open audacity.com when Audacity is installed locally.\n    if wants_browserish:\n        site_name = _candidate_site_name(request)\n        if site_name:\n            url = _resolve_site_via_web(site_name)\n            if url:\n                recipe = {"primitive": "open_url", "value": url}\n                result = _execute_skill_recipe(recipe)\n                if result.get("ok"):\n                    _remember_skill(request, recipe, "web-discovery")\n                    result["message"] = "learned web skill"\n                return result\n\n    folder = _resolve_existing_folder(request)\n    if folder:\n        recipe = {"primitive": "open_folder", "value": folder}\n        result = _execute_skill_recipe(recipe)\n        if result.get("ok"):\n            _remember_skill(request, recipe, "local-folder")\n            result["message"] = "learned folder skill"\n        return result\n\n    if wants_launch:\n        app_name = _candidate_app_name(request)\n        app_path = _resolve_installed_app(app_name)\n        if app_path:\n            recipe = {"primitive": "launch_app", "value": app_path}\n            result = _execute_skill_recipe(recipe)\n            if result.get("ok"):\n                _remember_skill(request, recipe, "installed-app-discovery")\n                result["message"] = "learned app skill"\n            return result\n\n    if wants_launch and not wants_browserish:\n        site_name = _candidate_site_name(request)\n        if site_name:\n            url = _resolve_site_via_web(site_name)\n            if url:\n                recipe = {"primitive": "open_url", "value": url}\n                result = _execute_skill_recipe(recipe)\n                if result.get("ok"):\n                    _remember_skill(request, recipe, "web-discovery-fallback")\n                    result["message"] = "learned web skill"\n                return result\n\n    return {"ok": False, "node_name": node, "message": "no safe skill recipe found"}\n'''
if old not in text:
    raise SystemExit("v0.8.4 skill resolution block not found")
text = text.replace(old, new, 1)
path.write_text(text, encoding="utf-8")
print("Applied v0.8.4 installed-app-first skill resolution hotfix")
